name: Generate Flutter Sample with Anthropic

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-sample:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic
        
    - name: Set ANTHROPIC_API_KEY
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> $GITHUB_ENV
        
    - name: Run sample generation script
      run: python scripts/generate_sample_anthropic.py
      
    - name: Commit and push if changes exist
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add samples/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add Flutter sample for $(date +'%Y-%m-%d')" && git push)
