name: Generate Anthropic Samples

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-samples:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Set up environment variables
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> $GITHUB_ENV
          
      - name: Generate Anthropic sample
        run: dart scripts/generate_sample_anthropic.dart
        
      - name: Update samples list
        run: dart scripts/update_samples_list.dart
        
      - name: Format JSON file
        run: |
          # Install jq for JSON formatting
          sudo apt-get install -y jq
          # Format the JSON file and save it back
          jq '.' assets/data/samples.json > temp.json && mv temp.json assets/data/samples.json
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Generated new Flutter sample"
          title: "Generated new Flutter sample"
          body: |
            Automated PR to add new Flutter sample generated by Anthropic Claude.
            
            This PR was automatically generated by the Generate Anthropic Samples workflow.
          branch: feature/new-anthropic-sample
          delete-branch: true
          
      - name: Enable Pull Request Automerge
        if: steps.create-pull-request.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge "${{ steps.create-pull-request.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
